//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.06.19 at 04:20:16 PM CEST
//

package com.intland.jenkins.jacoco.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "sessioninfo", "group", "_package", "counter" })
@XmlRootElement(name = "report")
public class Report {

	@XmlElement(required = true)
	protected List<Sessioninfo> sessioninfo;
	@XmlElement(name = "package")
	protected List<Package> _package;
	@XmlElement(name = "group")
	private List<Group> group;
	@XmlElement(required = true)
	protected List<Counter> counter;
	@XmlAttribute(name = "name")
	protected String name;

	/**
	 * Gets the value of the sessioninfo property.
	 */
	public List<Sessioninfo> getSessioninfo() {
		if (this.sessioninfo == null) {
			this.sessioninfo = new ArrayList<Sessioninfo>();
		}
		return this.sessioninfo;
	}

	/**
	 * Gets the value of the package property.
	 *
	 */
	public List<Package> getPackage() {
		if (this._package == null) {
			this._package = new ArrayList<Package>();
		}
		return this._package;
	}

	/**
	 * Gets the value of the counter property.
	 *
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the counter property.
	 *
	 * <p>
	 * For example, to add a new item, do as follows:
	 *
	 * <pre>
	 * getCounter().add(newItem);
	 * </pre>
	 *
	 *
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Report.Counter }
	 *
	 *
	 */
	public List<Counter> getCounter() {
		if (this.counter == null) {
			this.counter = new ArrayList<Counter>();
		}
		return this.counter;
	}

	/**
	 * Gets the value of the name property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the value of the name property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setName(String value) {
		this.name = value;
	}

	public List<Group> getGroup() {
		return this.group;
	}

	public void setGroup(List<Group> group) {
		this.group = group;
	}

}
