//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.30 at 04:15:50 PM CEST
//

package com.intland.jenkins.gcovr.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}sources" minOccurs="0"/>
 *         &lt;element ref="{}packages"/>
 *       &lt;/sequence>
 *       &lt;attribute name="line-rate" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="branch-rate" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="timestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "sources", "packages" })
@XmlRootElement(name = "coverage")
public class Coverage {

	protected Sources sources;
	@XmlElement(required = true)
	protected Packages packages;
	@XmlAttribute(name = "line-rate", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String lineRate;
	@XmlAttribute(name = "branch-rate", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String branchRate;
	@XmlAttribute(name = "version", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String version;
	@XmlAttribute(name = "timestamp", required = true)
	@XmlSchemaType(name = "anySimpleType")
	protected String timestamp;

	/**
	 * Gets the value of the sources property.
	 * 
	 * @return possible object is {@link Sources }
	 * 
	 */
	public Sources getSources() {
		return this.sources;
	}

	/**
	 * Sets the value of the sources property.
	 * 
	 * @param value
	 *            allowed object is {@link Sources }
	 * 
	 */
	public void setSources(Sources value) {
		this.sources = value;
	}

	/**
	 * Gets the value of the packages property.
	 * 
	 * @return possible object is {@link Packages }
	 * 
	 */
	public Packages getPackages() {
		return this.packages;
	}

	/**
	 * Sets the value of the packages property.
	 * 
	 * @param value
	 *            allowed object is {@link Packages }
	 * 
	 */
	public void setPackages(Packages value) {
		this.packages = value;
	}

	/**
	 * Gets the value of the lineRate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLineRate() {
		return this.lineRate;
	}

	/**
	 * Sets the value of the lineRate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setLineRate(String value) {
		this.lineRate = value;
	}

	/**
	 * Gets the value of the branchRate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBranchRate() {
		return this.branchRate;
	}

	/**
	 * Sets the value of the branchRate property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBranchRate(String value) {
		this.branchRate = value;
	}

	/**
	 * Gets the value of the version property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getVersion() {
		return this.version;
	}

	/**
	 * Sets the value of the version property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setVersion(String value) {
		this.version = value;
	}

	/**
	 * Gets the value of the timestamp property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTimestamp() {
		return this.timestamp;
	}

	/**
	 * Sets the value of the timestamp property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTimestamp(String value) {
		this.timestamp = value;
	}

}
