//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.30 at 04:15:50 PM CEST
//

package com.intland.jenkins.gcovr.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the generated package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _Source_QNAME = new QName("", "source");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: generated
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Methods }
	 * 
	 */
	public Methods createMethods() {
		return new Methods();
	}

	/**
	 * Create an instance of {@link Method }
	 * 
	 */
	public Method createMethod() {
		return new Method();
	}

	/**
	 * Create an instance of {@link Lines }
	 * 
	 */
	public Lines createLines() {
		return new Lines();
	}

	/**
	 * Create an instance of {@link Line }
	 * 
	 */
	public Line createLine() {
		return new Line();
	}

	/**
	 * Create an instance of {@link Conditions }
	 * 
	 */
	public Conditions createConditions() {
		return new Conditions();
	}

	/**
	 * Create an instance of {@link Condition }
	 * 
	 */
	public Condition createCondition() {
		return new Condition();
	}

	/**
	 * Create an instance of {@link Packages }
	 * 
	 */
	public Packages createPackages() {
		return new Packages();
	}

	/**
	 * Create an instance of {@link Package }
	 * 
	 */
	public Package createPackage() {
		return new Package();
	}

	/**
	 * Create an instance of {@link Classes }
	 * 
	 */
	public Classes createClasses() {
		return new Classes();
	}

	/**
	 * Create an instance of {@link ClassesType }
	 * 
	 */
	public ClassesType createClassesType() {
		return new ClassesType();
	}

	/**
	 * Create an instance of {@link Class }
	 * 
	 */
	public Class createClass() {
		return new Class();
	}

	/**
	 * Create an instance of {@link Sources }
	 * 
	 */
	public Sources createSources() {
		return new Sources();
	}

	/**
	 * Create an instance of {@link Coverage }
	 * 
	 */
	public Coverage createCoverage() {
		return new Coverage();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }
	 * {@code >}}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "source")
	public JAXBElement<String> createSource(String value) {
		return new JAXBElement<String>(_Source_QNAME, String.class, null, value);
	}

}
